server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config, classpath:/config/{application}, file:./config, file:./config/{application}
  profiles:
    active: native
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
