version: '3.3'
services:
  postgres:
    image: postgres:14
    container_name: postgres-library-microservices
    environment:
      POSTGRES_DATABASE: library
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
    restart: always