spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/library
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    jpa:
      hibernate:
        ddl-auto: none
server:
  port: 8083