server:
  port: 8081
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:postgresql://localhost:5430/library
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#eureka:
#  client:
#    service-url: localhost:8761
